Fix for report

diff --git a/.github/workflows/01-ci-e2e.yaml b/.github/workflows/01-ci-e2e.yaml
--- a/.github/workflows/01-ci-e2e.yaml
+++ b/.github/workflows/01-ci-e2e.yaml
@@ -20,6 +20,8 @@ jobs:
     steps:
       - name: Check out repository code
         uses: actions/checkout@v2
+      - name: Git init
+        run: git init
 
       - name: Install dependencies
         run: npm install
@@ -30,17 +32,11 @@ jobs:
           API_BASE_PATH: /api
           API_SECRET: ${{ secrets.API_SECRET }}
           DB_URL: postgres://postgres:postgres@postgres:5432/postgres
-
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v2
-        if: always() # always run even if the previous step fails
-        with:
-          report_paths: 'reports/jest-*.xml'
       
-      # - name: Test Report
-      #   uses: dorny/test-reporter@v1
-      #   if: success() || failure()    # run this step even if previous step failed
-      #   with:
-      #     name: JEST Tests            # Name of the check run which will be created
-      #     path: reports/jest-*.xml    # Path to test results
-      #     reporter: jest-junit        # Format of test results
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: reports/jest-*.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
